// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-I7flOMlQJWe3MceE-OSnlBaHXX0tk0',
    appId: '1:299646351783:web:5a288d069e440d43801e82',
    messagingSenderId: '299646351783',
    projectId: 'spectrum-medical-logistics',
    authDomain: 'spectrum-medical-logistics.firebaseapp.com',
    storageBucket: 'spectrum-medical-logistics.firebasestorage.app',
    measurementId: 'G-G2XZLL6NZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYrybNLuTNY8Nd1hb0uKFzqmmepZII8Gg',
    appId: '1:299646351783:android:0ee88ddd85aea0cd801e82',
    messagingSenderId: '299646351783',
    projectId: 'spectrum-medical-logistics',
    storageBucket: 'spectrum-medical-logistics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ2N8Mrq2kL3RzETNUp47Rnn0hNPBrtck',
    appId: '1:299646351783:ios:ebb7fb7e2568de0f801e82',
    messagingSenderId: '299646351783',
    projectId: 'spectrum-medical-logistics',
    storageBucket: 'spectrum-medical-logistics.firebasestorage.app',
    iosBundleId: 'com.example.spectrumMedicalLogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ2N8Mrq2kL3RzETNUp47Rnn0hNPBrtck',
    appId: '1:299646351783:ios:ebb7fb7e2568de0f801e82',
    messagingSenderId: '299646351783',
    projectId: 'spectrum-medical-logistics',
    storageBucket: 'spectrum-medical-logistics.firebasestorage.app',
    iosBundleId: 'com.example.spectrumMedicalLogistics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA-I7flOMlQJWe3MceE-OSnlBaHXX0tk0',
    appId: '1:299646351783:web:fc7f6116a5b8a6f5801e82',
    messagingSenderId: '299646351783',
    projectId: 'spectrum-medical-logistics',
    authDomain: 'spectrum-medical-logistics.firebaseapp.com',
    storageBucket: 'spectrum-medical-logistics.firebasestorage.app',
    measurementId: 'G-JJEZ1XKP2T',
  );
}
