import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file exists (generated by flutterfire configure)

// Theme and Constants
import 'package:spectrum_medical_logistics/theme/app_theme.dart';
import 'package:spectrum_medical_logistics/constants/app_constants.dart';

// Screens
import 'package:spectrum_medical_logistics/screens/home_screen.dart';
import 'package:spectrum_medical_logistics/screens/auth_screen.dart'; 
// Add your other screen imports here...

void main() async {
  // CRITICAL: Initialize Firebase before the app starts
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SpectrumApp());
}

// --- NAVIGATION PATHS ---
const Map<String, String> _navPaths = {
  'Home': '/',
  'SignIn': '/sign-in',
  'SignUp': '/sign-up',
};

// --- GO ROUTER SETUP ---
final GoRouter _router = GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: _navPaths['Home']!,
      builder: (context, state) => const HomeScreen(),
    ),
    GoRoute(
      path: _navPaths['SignIn']!,
      builder: (context, state) => const AuthScreen(isSignUp: false),
    ),
    GoRoute(
      path: _navPaths['SignUp']!,
      builder: (context, state) => const AuthScreen(isSignUp: true),
    ),
  ],
);

class SpectrumApp extends StatelessWidget {
  const SpectrumApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: AppConstants.appTitle,
      theme: getAppTheme(),
      routerConfig: _router,
      debugShowCheckedModeBanner: false,
    );
  }
}